# ---- STAGE 1 : Build ----
FROM node:20-alpine AS builder

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .
COPY prisma ./prisma

ARG DATABASE_URL
ENV DATABASE_URL=$DATABASE_URL

RUN npx prisma generate
RUN npm run build

# ---- STAGE 2 : Production ----
FROM node:20-alpine AS production

WORKDIR /app

COPY package*.json ./
RUN npm install --omit=dev

COPY --from=builder /app/dist ./dist
COPY prisma ./prisma

# 👇 Le bon chemin d'output Prisma
COPY --from=builder /app/src/generated ./src/generated

ENV NODE_ENV=production

EXPOSE 3000

CMD ["node", "dist/src/main.js"]